name: Deploy linkshare

on:
 push:
   branches:
     - main

jobs:
 Deploy:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Setup node
       uses: actions/setup-node@v2

     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION}}
     - name: Install dependencies
       run: npm install

     - name: Build 
       run: npm run build

     - name: Deploy linkshare S3 bucket
       run: aws s3 sync ./build/ s3://${{secrets.AWS_BUCKET}} --exclude ".git/*" --exclude ".gitignore" --exclude ".gitattributes" --exclude ".github/*"
